### ISSUE TITLE
1fichier

### ISSUE THREAD

**Issue by Mad-sl67** [marcussacana/DirectPackageInstaller#16]
I get "failed to get the pkg info" whenever i put 1fichier link ?

**Comment by marcussacana** [comment]
1 - 1Fichier links must be extracted PKG files, RAR/7z files don't works.
2 - You verified if your ip is blocked by the 1fichier? that cooldown can cause that.
if everything looks fine, send me the link to my email ddtank.marcus@gmail.com and I will check what is happening.

**Comment by marcussacana** [comment]
I think I know what is the problem

**Comment by marcussacana** [comment]
I think it's fixed in the lastest update, try it.

**Comment by Mad-sl67** [comment]
Should i redownload directpackageinstaller or just use the one i already have ?

**Comment by marcussacana** [comment]
anyway, the last version is the version 6.0.13

**Comment by Mad-sl67** [comment]
I'm on v 6.0.13 and still not working
Tried doing it in direct and undirect link of 1fichier and still nothing

**Comment by marcussacana** [comment]
Ohh sorry, then isn't a bug but a missing feature.
Currently the CLI is very basic yet, it support only direct links.

**Comment by Mad-sl67** [comment]
Okay later when u have time u can tell me how to this trick

**Comment by marcussacana** [comment]
Support for file hosting links from CLI added.
Try it.

**Comment by Mad-sl67** [comment]
> Support for file hosting links from CLI added. Try it.

Actually it worked
I got the game pkg on my ps4 notifcation
But the game keeps calculating without downloading
After that i got this error message
Now i have to wait 60 min to try again
![IMG_20220531_233221](https://user-images.githubusercontent.com/99123936/171294914-cecd8aa0-d8ef-4abd-8e2b-034e13c13a23.jpg)
![IMG_20220531_233049_1](https://user-images.githubusercontent.com/99123936/171294939-a043f045-396e-404f-addd-c6a3bc6a178b.jpg)
![IMG_20220531_233042](https://user-images.githubusercontent.com/99123936/171294968-dd2a6f8b-91cc-46e0-aa3d-9292fc2440be.jpg)
![IMG_20220531_233028](https://user-images.githubusercontent.com/99123936/171295038-02c8753e-cc03-4d9c-bf24-b6f9fa2a0fdc.jpg)

**Comment by marcussacana** [comment]
Next time try run `dotnet DirectPackageInstaller.Desktop.dll YOUR_URL`

**Comment by Mad-sl67** [comment]
Okay after cooldown i will execute
But should i put my IP in command too ?
Or just like this : 
dotnet DirectPackageInstaller.Desktop.dll "https://1fichier.com/?ddjxj1xn24ml66dim41o"

**Comment by marcussacana** [comment]
Some things, as well.
- Ensure the DirectPackageInstaller has permission to write big files in his folder.
- Ensure you have free space of the size of the game that you're downloading.
- If this is a android linux emulator, check if the same thing happens in the UI.

This is a unmanaged exception that you had, means the problem is out of my code and probably out of my control.
We will need test a bit more to see if there is something that we can do, because on my PC that bug didn't happens

**Comment by marcussacana** [comment]
You don't need put your IP, the DPI detect it automatically, you only need put the IP if that detection for some reason fails or you have more of one PS4 in your network.

**Comment by marcussacana** [comment]
As you can see, it's working here, then the bug is hard to me reproduce.
![image](https://user-images.githubusercontent.com/10576957/171296465-ccddd1d8-ce2a-4a5d-9e74-a8765c666c8a.png)

**Comment by Mad-sl67** [comment]
![IMG_20220602_014710](https://user-images.githubusercontent.com/99123936/171524513-4f9d445c-f1a3-4899-b31d-475d91c10a8f.jpg)

**Comment by marcussacana** [comment]
when you get this error, in the DPI folder should have a directory called "Temp" and inside this directory should have some random files, give me a screenshot of what files and his sizes.

**Comment by marcussacana** [comment]
I'm deleting some comments because you're showing the download link.

**Comment by Mad-sl67** [comment]
![IMG_20220602_032639](https://user-images.githubusercontent.com/99123936/171537649-dfe635b6-f49c-4402-bdb7-4de9cdf072fc.jpg)

**Comment by Mad-sl67** [comment]
What is the problem exactly and can it be fixed somehow ?

**Comment by marcussacana** [comment]
1,3GB huh, the DirectPackageInstaller have write permissions then.
This game looks like is 34GB, your phone has free space for that?
In the 1Fichier the PKG is fully downloaded in your device in that temp folder.

**Comment by marcussacana** [comment]
I'm not sure about reason of the problem yet.
There's no crash log or anything after all.
Maybe you may try build the DPI as debug (Since is under ARM)
and use check if there's a info in the DPI-Server.log file

**Comment by Mad-sl67** [comment]
I see!
The problem is that most of the links are in 1fichier
And for zippyshare it's multi rar files as u know ..
It's rare or maybe impossible to find direct pkg links except 1fichier

**Comment by marcussacana** [comment]
you will need use allderbid to download from 1fichier without cache the PKG.

**Comment by Mad-sl67** [comment]
![IMG_20220602_182522](https://user-images.githubusercontent.com/99123936/171688396-97c97173-b148-4f4c-b204-fbf17b25cae6.jpg)
Aldebrid method sounds good for me
I created acount there .. i put the 1fichier link and i got a direct link from it
But didn't work when i put it in DPI 
Is this got something to do with that API code ?
Cuz i don't know how to get one or how to activate it

**Comment by Mad-sl67** [comment]
Hey
I tried
./DirectPackageInstaller.Desktop -Server 192.168.1.2 "Url" command and finally after all these days of trying finally worked ! Thank u

**Comment by Mad-sl67** [comment]
Hey
I tried
./DirectPackageInstaller.Desktop -Server IP "Url" command and finally after all these days of trying finally worked ! Thank u

**Comment by marcussacana** [comment]
> ![IMG_20220602_182522](https://user-images.githubusercontent.com/99123936/171688396-97c97173-b148-4f4c-b204-fbf17b25cae6.jpg) Alldebrid method sounds good for me I created acount there .. i put the 1fichier link and i got a direct link from it But didn't work when i put it in DPI Is this got something to do with that API code ? Cuz i don't know how to get one or how to activate it

Looks like this is a bug, I may take a look in the problem, send the link that give error to my email: ddtank.marcus@gmail.com

**Comment by marcussacana** [comment]
If you try use the UI disable the `Segmented Mode` as well, since that will force the pkg be cached in your phone.

**Comment by Mad-sl67** [comment]
I found a website that generates free 1fichier direct link but it's not supported in DPI
Can i share the link ? And can u add it in the next update ? It will be a really big help for me and for other users as well

**Comment by marcussacana** [comment]
If don't works should be because they url expires after one connections or don't have seek support...
Send to my email and I will take a look at least. ddtank.marcus@gmail.com

**Comment by Mad-sl67** [comment]
Sent

**Comment by marcussacana** [comment]
I take a look and this server don't works because don't have support for patial requests.
That can be 'solved' with the same 1fichier method, but will require free space just like the 1fichier as well.
No point in add support after that.

**Comment by marcussacana** [comment]
6.1.1 has a better 1fichier support if you enable the AllowReconnection and meet the requeriments, closing this for now.

**Comment by Mad-sl67** [comment]
> 6.1.1 has a better 1fichier support if you enable the AllowReconnection and meet the requeriments, closing this for now.

I tried this new update but i'm still getting the same error
I think the problem is because the pkg cashe is still higher than my phone's storage

**Comment by marcussacana** [comment]
Yep, that isn't solved at all, currently I can only recommend use a big SDCard and move the DPI to the SDCard
